Association
Thermiee/School-library pull request #3
Opened 2022-05-12 13:01 UTC by Thermiee

In this pull request, I:

- Created a class `Classroom` with the following:
  - `@label` instance variable, initialized in the constructor
  - Setter and getter for `@label`
-  Created the `has-many/belongs-to` relationship between `Classroom` and `Student`. The following was implemented:
   - Created the `has-many` side (a classroom has many students)
   - Created the `belongs-to` side (a student belongs to a classroom)
- Created a class `Book` with the following:
   - `@title` and `@author` instance variables, initialized in the constructor
   - Setters and getters for instance variables
- Created a class `Rental` with the following
   - `@date` instance variable, initialized in the constructor
   - Setter and getter for `@date`
- Created the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`. The following was implemented:
  - Created the `has-many` side of `Book` and `Rental` (a book has many rentals)
  - Created the ` belongs-to` side of `Rental` and `Book` (a rental belongs to a book)
  - Created the `has-many` side of `Person` and `Rental` (a person has many rentals)
  - Created the `belongs-to` side of `Rental` and `Person` (a rental belongs to a person)
  - Modified the constructor of `Rental` so `Book` and `Person` are set in it.

2022-05-12 13:24 UTC, t-yanick requested changes
Hi @Thermiee, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 13:24 UTC, t-yanick commented on person.rb
- [x] To implement the `has-many` side of the relationship between `Person` and `Rental`, a method for adding rentals should be present in the `Person` class like so;
```ruby
  def add_rental(book, date)
    Rental.new(date, book, self)
  end
```
Please kindly fix that.

2022-05-12 13:24 UTC, t-yanick commented on classroom.rb
> +  end
- [x] To implement the `belongs-to` association between `Classroom` and `Student`, `a method that serves as the 'belongs-to' side (a student belongs to a classroom)` should be present in the `Student` class. Something like so:
```ruby
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```
Please kindly fix that.

2022-05-13 13:29 UTC, Deepakdanger requested changes
Hi @Thermiee, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 13:29 UTC, Deepakdanger commented on book.rb
> +  end
- [ ] [OPTIONAL] While creating rental in `class Book`. we don't require to pass  `book` here. kindly fix it .
- for ex:- 
```
 def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end
```

2022-05-13 13:29 UTC, Deepakdanger commented on rental.rb
> +  attr_reader :person, :book
- [ ] [ OPTIONAL] It is required to have `:person, :book` inside `attr_accessor`. 
- **Requirement** `attr_accessor :date, :book, :person`

2022-05-13 13:29 UTC, Deepakdanger commented on book.rb
> +  end
- [ ] [**REQUIRED**] As requested by the previous reviewer, To implement the `belongs-to` association between `Classroom` and `Student`, a method that serves as the 'belongs-to' side (a student belongs to a classroom) should be present in the Student class.
- Kindly create a new file and write this code there, For ex:- 
- * When setting the classroom for a student it also adds it to the classrooms' students:

```ruby
class Student < Person
  attr_reader :classroom
  .
  .
  # *Check for a method that serves as the 'belongs-to' side (a student belongs to a classroom). Link to the article with examples: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
end
```

2022-05-13 17:47 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @Thermiee 👋🏻, 

Good job on making the requested changes 👍🏻.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 18:16 UTC, merged